### ISSUE TITLE
Recommandation to insert the FeatureDiscovery widget in the MaterialApp builder is not the best

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [axel-op/feature_discovery#12]
I did not even notice this before, or rather I did not think about it, but the recommondation to pass the `FeatureDiscovery` widget in the builder of `MaterialApp` (as can be seen [here](https://github.com/axel-op/feature_discovery/blob/master/example/lib/main.dart#L30) and [here](https://github.com/axel-op/feature_discovery/blob/master/README.md#using)) seems a bit off to me.

@axel-op 

Maybe you can think of a reason why this would be necessary, but in my view this only has drawbacks:

 * Unnecessary rebuilds when the `builder` is called.

 * Unnecessarily inserting the widget multiple times for every route.

 * A bunch of additional syntax.

I am currently going over the README and I will just recommend to wrap the `MaterialApp` with `FeatureDiscovery` instead.

**Comment by axel-op** [comment]
That actually also bothered me, and your arguments are really convincing. 

> I am currently going over the README and I will just recommend to wrap the MaterialApp with FeatureDiscovery instead.

That's actually what I did in one of my personal projects.
