### ISSUE TITLE
Assign DescribedFeatureOverlay instance to step

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [axel-op/feature_discovery#16]
Following up on [the following](https://github.com/axel-op/feature_discovery/commit/378fbeaf3554c7a9528ee45fd4c00484c8785d33#r34912564):

> Why don't you use the object's instances directly as values?

If we assign a particular `State` object to each step in the feature discovery process, we can fix a hand full of issues:

 * No animation for dismissal when it is called programmatically: https://github.com/axel-op/feature_discovery/blob/f4fd0f700081e49ca71396b4370ef2c86fe384fc/lib/src/feature_discovery.dart#L79
   This implementation will notify all dependants and the current overlay will hide immediately.

 * No animation for `markStepComplete`: https://github.com/axel-op/feature_discovery/blob/f4fd0f700081e49ca71396b4370ef2c86fe384fc/lib/src/feature_discovery.dart#L66
   Same as above.

 * No control over what widget is shown if `allowShowingDuplicate == false`: https://github.com/axel-op/feature_discovery/blob/f4fd0f700081e49ca71396b4370ef2c86fe384fc/lib/src/feature_discovery.dart#L106

If we assigned a particular `State` to a step in the feature discovery process, we could call it to dismiss and activate, just like it does itself when the user taps it.  
Additionally, in the assigning process, we would be able to control what `State` is assigned. I think the best option here is to assign the latest state that was inserted into the tree (in `initState`), but always make sure that it is still mounted (in `dispose`).  
Maybe this is not very safe, meaning that the assigned widget might not be visible, but I think that this could work.

@axel-op This is not urgent at all and a pretty big change. I am not exactly sure how to do it. I think that discussing the implementation beforehand might be useful.

**Comment by axel-op** [comment]
What about multiple widgets with the same featureId ?
________________________________

**Comment by creativecreatorormaybenot** [comment]
@axel-op `allowShowingDuplicate` would still exist. If `allowShowingDuplicate` is `true`, we can just add to a `List` of assignees for each step, i.e. `Map<String, List<State>>`, and if it is set to `false`, the `State` will simply not be added to that `List` if the `List` is not yet empty.

**Comment by axel-op** [comment]
Right. Here's another suggestion: what about replacing the feature ids by keys?
We could make the key of `DescribedFeatureOverlay` a required parameter, and constrain its type to be a GlobalKey so we could directly access the state from it.
________________________________

**Comment by axel-op** [comment]
Right. Here's another suggestion: what about replacing the feature ids by keys?
We could make the key of `DescribedFeatureOverlay` a required parameter, and constrain its type to be a `GlobalKey` so we could directly access the state from it.

**Comment by axel-op** [comment]
But actually either way I think it's an anti pattern of the Inherited widget model. We should found another solution.

**Comment by creativecreatorormaybenot** [comment]
Well, `GlobalKey` certainly is that. I think updating a value in our global state is not. Basically, the dependants are notified, one dependant updates a value, saying "I took care of this" and then another dependant can look up this value.
