### ISSUE TITLE
New tests fail with the current implementation

### ISSUE THREAD

**Issue by axel-op** [axel-op/feature_discovery#21]
I added tests for some special case in the branch https://github.com/axel-op/feature_discovery/tree/testing

I noticed that `markStepComplete` doesn't work properly with these tests because the tests can't find the next overlay after it has been called (it's like it's not displayed at all).

However on a device this seems to work fine.

**Comment by creativecreatorormaybenot** [comment]
I would suggest that you just merge your implementation if you plan on working on the plugin further. That would get rid of a lot of difficulties.

**Comment by axel-op** [comment]
Closed because #20 has been merged
