### ISSUE TITLE
featureId != null is not true

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [axel-op/feature_discovery#29]
I wanted to test your implementation as it you have finished it now, but starting the example and trying to dismiss or complete the "Find the fastest route" step does not work.  
The example app is completely bricked for me, no matter what I try to do.

Apparently, `_activeStepId` is `null`. I wanted to create this issue first before debugging as you might know why this is happening.

**Comment by axel-op** [comment]
Ok so I retrieved all the last merge-commits and tested it to see at which point the bug has been introduced, and it seems that it started with commit 1dec6d9a973c89de14a4369bd863ca09426560fc

**Comment by axel-op** [comment]
The thing is, everything seems fine in the branch https://github.com/axel-op/feature_discovery/tree/with-streams
So the bug may have been introduced while merging this branch into master

**Comment by axel-op** [comment]
I found it, the bug appears at commit e2c6910d1d4ab6e28ba41dbbe1b03a4d62aa1f54

**Comment by axel-op** [comment]
@creativecreatorormaybenot Ok so here's why this is happening: on [this line](https://github.com/axel-op/feature_discovery/blob/master/example/lib/main.dart#L30) of the example, the `FeatureDiscovery` widget is placed in `builder`'s `MaterialApp` parameter, and it seems that it is often rebuilt, so calls to `ancestorWidgetOfExactType` return a different widget each time. 

This shouldn't happen in situations where this is implemented as in the README.

**Comment by creativecreatorormaybenot** [comment]
I will test it later today. To be honest, to me it seems like rebuilds of the `builder` **should not** brick the feature discovery process because it should not actually reinsert the state. You might want to look into it (I might later as well) because this is the way the old implementation was used and it worked completely fine.

**Comment by creativecreatorormaybenot** [comment]
@axel-op That did not do it. I would have been confused if it had done it as I mentioned.

When I run the example, it is completely bricked, meaning that the feature overlay is showing and pulsing, but neither tapping the tap target nor trying to dismiss works. If I rotate the device (forcing a rebuild), the tap target tap will still not throw anything, but dismissing will throw `featureId != null is not true`.

**Comment by axel-op** [comment]
> @axel-op That did not do it. I would have been confused if it had done it as I mentioned.
> 
> When I run the example, it is completely bricked, meaning that the feature overlay is showing and pulsing, but neither tapping the tap target nor trying to dismiss works. If I rotate the device (forcing a rebuild), the tap target tap will still not throw anything, but dismissing will throw `featureId != null is not true`.

Are you sure about that? Because that works totally fine for me, even when I rotate my device.

**Comment by axel-op** [comment]
> @axel-op That did not do it. I would have been confused if it had done it as I mentioned.
> 
> When I run the example, it is completely bricked, meaning that the feature overlay is showing and pulsing, but neither tapping the tap target nor trying to dismiss works. If I rotate the device (forcing a rebuild), the tap target tap will still not throw anything, but dismissing will throw `featureId != null is not true`.

Are you sure about that? Because that works totally fine for me, even when I rotate my device.

**Comment by creativecreatorormaybenot** [comment]
@axel-op What emulator, branch etc. are you running?  
But regardless of that, what you said about the `builder` code cannot be correct 😕

**Comment by axel-op** [comment]
@creativecreatorormaybenot I ran it on the 'example-fix' branch, on an emulator as well as on my personal physical device. 
I cannot recreate this issue

**Comment by creativecreatorormaybenot** [comment]
I mean what emulator specifically and maybe what version of Flutter?

Happens on an Android Q Emulator (Flutter `v1.10.6-pre67`).

**Comment by axel-op** [comment]
Well I'm still using the 1.9.1+hotfix.2 version of Flutter as I'm on the stable channel

**Comment by creativecreatorormaybenot** [comment]
@axel-op Mind trying? `flutter channel master`, then run and then `flutter channel stable` should just work fine.

**Comment by axel-op** [comment]
Yeah I know but in the case it would fail, it could be then sort of a bug due to the fact that the master channel hasn't been fully tested...

**Comment by axel-op** [comment]
@creativecreatorormaybenot So I upgraded to version 1.10.7-pre.41 only to test this and… I found nothing! Everything works fine for me. I tested it with Android 8.1 and 9 but not Q though.

**Comment by axel-op** [comment]
@creativecreatorormaybenot Did you close this because the last commits solve your issue or … ?

**Comment by creativecreatorormaybenot** [comment]
@axel-op It was flaky and I could not reproduce it with the latest master version.
