### ISSUE TITLE
Feature Overlay not properly aligned when used inside Scaffold's 'floatingActionButton'

### ISSUE THREAD

**Issue by axel-op** [axel-op/feature_discovery#5]
## Step to reproduce
Place a `DescribedFeatureOverlay`, with a FAB as its child, inside a `Scaffold`'s `floatingActionButton` parameter. 

## What happens
Depending on the size of the screen, the overlay is not always properly aligned with its child.

**Comment by creativecreatorormaybenot** [comment]
Can you elaborate? I personally do not experience this. Neither do I experience #6.

**Comment by axel-op** [comment]
You're right, I tried to recreate this on other apps but I couldn't. I must have messed up somewhere. 
Anyway, I found a workaround and am going to close this.
