### ISSUE TITLE
Dismiss animation is not showing

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [axel-op/feature_discovery#7]
The dismiss animation should look [like this](https://material.io/archive/guidelines/assets/0B4kv-3uZbS1qZjRWMUdLX1pVVVU/useredu-er-featuredisc-motion-dismiss-loop.webm).

For me it just disappears at the moment.

**Comment by creativecreatorormaybenot** [comment]
Nevermind, the only issue here is that `FeatureDiscovery.dismiss` does not show the dismiss animation.  

However, I think that a change like this is out of scope for now, hence, I will close this. (I could add this when I implement something like assignees again)

**Comment by axel-op** [comment]
Can you explain why this is happening?

**Comment by creativecreatorormaybenot** [comment]
I explained it in #16.

**Comment by axel-op** [comment]
Could you explain it more?

**Comment by creativecreatorormaybenot** [comment]
@axel-op https://github.com/axel-op/feature_discovery/blob/b3df34410956934386edfa1cc0f121f849a29b36/lib/src/feature_discovery.dart#L348

This cannot be called when dismissing because the dismissal [happens in `_FeatureDiscoveryState`](https://github.com/axel-op/feature_discovery/blob/b3df34410956934386edfa1cc0f121f849a29b36/lib/src/feature_discovery.dart#L79), which is essentially just clears the `activeStepIndex` & `steps` and notifies dependants. The overlay will just disappear because its `featureId` does not match the `activeStepIndex` anymore.  
The same applies for [`markStepComplete`](https://github.com/axel-op/feature_discovery/blob/b3df34410956934386edfa1cc0f121f849a29b36/lib/src/feature_discovery.dart#L66). 

We would need to have a reference to the `_DescribedFeatureOverlayState` to call `dismiss` and `activate` there. That should be possible using a `GlobalKey` right now, but the logic for that if there are multiple steps involved is mad and it should be a package feature that the `dismiss` and `activate` animations play even when dismissing using `FeatureDiscovery`.

**Comment by axel-op** [comment]
What about calling the `dismiss` method in this bloc?
https://github.com/axel-op/feature_discovery/blob/b3df34410956934386edfa1cc0f121f849a29b36/lib/src/feature_discovery.dart#L335

**Comment by creativecreatorormaybenot** [comment]
@axel-op Well, we would need to somehow pass that it is a dismissal or activation and then you also need to assure that `markStepComplete` and `dismiss` are not called again at the end of the animation, but it would be a reasonable solution.  
Actually it would be way better to just have a different variable for this and then let the animation finish things do the same logic no matter what.
I will sketch something in a moment if that is okay for you.

**Comment by creativecreatorormaybenot** [comment]
There is just the issue that we cannot be sure that the dismissal or activation was successful because it relies on a dependant. I think that I would add a public-facing clear method to ensure that there is always a way to clear the feature discovery.

**Comment by axel-op** [comment]
I don't understand what you mean here:
> Well, we would need to somehow pass that it is a dismissal or activation

And here:
> There is just the issue that we cannot be sure that the dismissal or activation was successful because it relies on a dependant.

**Comment by creativecreatorormaybenot** [comment]
I will just sketch an implementation..
