### ISSUE TITLE
Update README & example

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [axel-op/feature_discovery#8]
With the recent breaking changes, the example and `README.md` are completely outdated.

I am going to rework them (tomorrow).

**Comment by axel-op** [comment]
What do you think about my last changes?

**Comment by creativecreatorormaybenot** [comment]
@axel-op It would be a lot easier to see if it was a PR, but I will take a look at the commits.

**Comment by axel-op** [comment]
Sorry I only thought about that after committing

**Comment by creativecreatorormaybenot** [comment]
There are a few typos here and there, in different files. I will make one PR for typos and to be honest, I would like to completely rephrase the README if that is okay. I would just propose my changes and then you could review that - the example looks fine, but I do not understand why `pubspec.lock` appeared again in the example as I added it to `.gitignore`.

**Comment by axel-op** [comment]
> the example looks fine, but I do not understand why pubspec.lock appeared again in the example as I added it to .gitignore.

I also added it in .gitignore, but then merging your version in my local repository I had a few conflicts, in particular with `pubspec.lock` so it's probably my fault
