### ISSUE TITLE
'discoverFeatures' doesn't work anymore when one of the overlays is dismissed

### ISSUE THREAD

**Issue by axel-op** [axel-op/feature_discovery#9]
## Steps to reproduce
Call `discoverFeatures` and dismiss one of the overlays instead of tapping on the target. 
Overlays are not displayed when `discoverFeatures` is called again (they are otherwise).

**Comment by creativecreatorormaybenot** [comment]
That is what I was seeing all the time! I could not get my head about why it sometimes would not display the overlay and sometimes it would. I am going to fix this.
(Fixed in #10 )
